# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'caudaltrescasos.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(594, 201)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayoutA_Nivel01 = QtGui.QVBoxLayout()
        self.verticalLayoutA_Nivel01.setObjectName(_fromUtf8("verticalLayoutA_Nivel01"))
        self.label_Titulo = QtGui.QLabel(Dialog)
        self.label_Titulo.setObjectName(_fromUtf8("label_Titulo"))
        self.verticalLayoutA_Nivel01.addWidget(self.label_Titulo)
        self.horizontalLayoutA_Nivel02 = QtGui.QHBoxLayout()
        self.horizontalLayoutA_Nivel02.setObjectName(_fromUtf8("horizontalLayoutA_Nivel02"))
        self.verticalLayoutA_Nivel03 = QtGui.QVBoxLayout()
        self.verticalLayoutA_Nivel03.setObjectName(_fromUtf8("verticalLayoutA_Nivel03"))
        self.horizontalLayoutA_Nivel04 = QtGui.QHBoxLayout()
        self.horizontalLayoutA_Nivel04.setObjectName(_fromUtf8("horizontalLayoutA_Nivel04"))
        self.GrupoA1verticalLayout_01 = QtGui.QVBoxLayout()
        self.GrupoA1verticalLayout_01.setObjectName(_fromUtf8("GrupoA1verticalLayout_01"))
        self.GrupoA1label01_Velocidad = QtGui.QLabel(Dialog)
        self.GrupoA1label01_Velocidad.setObjectName(_fromUtf8("GrupoA1label01_Velocidad"))
        self.GrupoA1verticalLayout_01.addWidget(self.GrupoA1label01_Velocidad)
        self.GrupoA1label02_Area = QtGui.QLabel(Dialog)
        self.GrupoA1label02_Area.setObjectName(_fromUtf8("GrupoA1label02_Area"))
        self.GrupoA1verticalLayout_01.addWidget(self.GrupoA1label02_Area)
        self.horizontalLayoutA_Nivel04.addLayout(self.GrupoA1verticalLayout_01)
        self.GrupoA2verticalLayout_02 = QtGui.QVBoxLayout()
        self.GrupoA2verticalLayout_02.setObjectName(_fromUtf8("GrupoA2verticalLayout_02"))
        self.GrupoA2line01_Velocidad = QtGui.QLineEdit(Dialog)
        self.GrupoA2line01_Velocidad.setObjectName(_fromUtf8("GrupoA2line01_Velocidad"))
        self.GrupoA2verticalLayout_02.addWidget(self.GrupoA2line01_Velocidad)
        self.GrupoA2line02_Area = QtGui.QLineEdit(Dialog)
        self.GrupoA2line02_Area.setObjectName(_fromUtf8("GrupoA2line02_Area"))
        self.GrupoA2verticalLayout_02.addWidget(self.GrupoA2line02_Area)
        self.horizontalLayoutA_Nivel04.addLayout(self.GrupoA2verticalLayout_02)
        self.GrupoA3verticalLayout_03 = QtGui.QVBoxLayout()
        self.GrupoA3verticalLayout_03.setObjectName(_fromUtf8("GrupoA3verticalLayout_03"))
        self.GrupoA3labelUnits01 = QtGui.QLabel(Dialog)
        self.GrupoA3labelUnits01.setObjectName(_fromUtf8("GrupoA3labelUnits01"))
        self.GrupoA3verticalLayout_03.addWidget(self.GrupoA3labelUnits01)
        self.GrupoA3labelUnits02 = QtGui.QLabel(Dialog)
        self.GrupoA3labelUnits02.setObjectName(_fromUtf8("GrupoA3labelUnits02"))
        self.GrupoA3verticalLayout_03.addWidget(self.GrupoA3labelUnits02)
        self.horizontalLayoutA_Nivel04.addLayout(self.GrupoA3verticalLayout_03)
        self.verticalLayoutA_Nivel03.addLayout(self.horizontalLayoutA_Nivel04)
        self.ButtonCalcularA = QtGui.QPushButton(Dialog)
        self.ButtonCalcularA.setObjectName(_fromUtf8("ButtonCalcularA"))
        self.verticalLayoutA_Nivel03.addWidget(self.ButtonCalcularA)
        self.labelFormulaA = QtGui.QLabel(Dialog)
        self.labelFormulaA.setObjectName(_fromUtf8("labelFormulaA"))
        self.verticalLayoutA_Nivel03.addWidget(self.labelFormulaA)
        self.labelResultadoCaudal = QtGui.QLabel(Dialog)
        self.labelResultadoCaudal.setText(_fromUtf8(""))
        self.labelResultadoCaudal.setObjectName(_fromUtf8("labelResultadoCaudal"))
        self.verticalLayoutA_Nivel03.addWidget(self.labelResultadoCaudal)
        self.horizontalLayoutA_Nivel02.addLayout(self.verticalLayoutA_Nivel03)
        self.verticalLayoutB_Nivel03 = QtGui.QVBoxLayout()
        self.verticalLayoutB_Nivel03.setObjectName(_fromUtf8("verticalLayoutB_Nivel03"))
        self.horizontalLayoutB_Nivel04 = QtGui.QHBoxLayout()
        self.horizontalLayoutB_Nivel04.setObjectName(_fromUtf8("horizontalLayoutB_Nivel04"))
        self.GrupoB1verticalLayout_01 = QtGui.QVBoxLayout()
        self.GrupoB1verticalLayout_01.setObjectName(_fromUtf8("GrupoB1verticalLayout_01"))
        self.GrupoB1label01_Caudal = QtGui.QLabel(Dialog)
        self.GrupoB1label01_Caudal.setObjectName(_fromUtf8("GrupoB1label01_Caudal"))
        self.GrupoB1verticalLayout_01.addWidget(self.GrupoB1label01_Caudal)
        self.GrupoB1label02_Area = QtGui.QLabel(Dialog)
        self.GrupoB1label02_Area.setObjectName(_fromUtf8("GrupoB1label02_Area"))
        self.GrupoB1verticalLayout_01.addWidget(self.GrupoB1label02_Area)
        self.horizontalLayoutB_Nivel04.addLayout(self.GrupoB1verticalLayout_01)
        self.GrupoB2verticalLayout_02 = QtGui.QVBoxLayout()
        self.GrupoB2verticalLayout_02.setObjectName(_fromUtf8("GrupoB2verticalLayout_02"))
        self.GrupoB2line01_Caudal = QtGui.QLineEdit(Dialog)
        self.GrupoB2line01_Caudal.setObjectName(_fromUtf8("GrupoB2line01_Caudal"))
        self.GrupoB2verticalLayout_02.addWidget(self.GrupoB2line01_Caudal)
        self.GrupoB2line02_Area = QtGui.QLineEdit(Dialog)
        self.GrupoB2line02_Area.setObjectName(_fromUtf8("GrupoB2line02_Area"))
        self.GrupoB2verticalLayout_02.addWidget(self.GrupoB2line02_Area)
        self.horizontalLayoutB_Nivel04.addLayout(self.GrupoB2verticalLayout_02)
        self.GrupoB3verticalLayout_03 = QtGui.QVBoxLayout()
        self.GrupoB3verticalLayout_03.setObjectName(_fromUtf8("GrupoB3verticalLayout_03"))
        self.GrupoB3labelUnits01 = QtGui.QLabel(Dialog)
        self.GrupoB3labelUnits01.setObjectName(_fromUtf8("GrupoB3labelUnits01"))
        self.GrupoB3verticalLayout_03.addWidget(self.GrupoB3labelUnits01)
        self.GrupoB3labelUnits02 = QtGui.QLabel(Dialog)
        self.GrupoB3labelUnits02.setObjectName(_fromUtf8("GrupoB3labelUnits02"))
        self.GrupoB3verticalLayout_03.addWidget(self.GrupoB3labelUnits02)
        self.horizontalLayoutB_Nivel04.addLayout(self.GrupoB3verticalLayout_03)
        self.verticalLayoutB_Nivel03.addLayout(self.horizontalLayoutB_Nivel04)
        self.ButtonCalcularB = QtGui.QPushButton(Dialog)
        self.ButtonCalcularB.setObjectName(_fromUtf8("ButtonCalcularB"))
        self.verticalLayoutB_Nivel03.addWidget(self.ButtonCalcularB)
        self.labelFormulaB = QtGui.QLabel(Dialog)
        self.labelFormulaB.setObjectName(_fromUtf8("labelFormulaB"))
        self.verticalLayoutB_Nivel03.addWidget(self.labelFormulaB)
        self.labelResultadoVelocidad = QtGui.QLabel(Dialog)
        self.labelResultadoVelocidad.setText(_fromUtf8(""))
        self.labelResultadoVelocidad.setObjectName(_fromUtf8("labelResultadoVelocidad"))
        self.verticalLayoutB_Nivel03.addWidget(self.labelResultadoVelocidad)
        self.horizontalLayoutA_Nivel02.addLayout(self.verticalLayoutB_Nivel03)
        self.verticalLayoutC_Nivel03 = QtGui.QVBoxLayout()
        self.verticalLayoutC_Nivel03.setObjectName(_fromUtf8("verticalLayoutC_Nivel03"))
        self.horizontalLayoutC_Nivel04 = QtGui.QHBoxLayout()
        self.horizontalLayoutC_Nivel04.setObjectName(_fromUtf8("horizontalLayoutC_Nivel04"))
        self.GrupoC1verticalLayout_01 = QtGui.QVBoxLayout()
        self.GrupoC1verticalLayout_01.setObjectName(_fromUtf8("GrupoC1verticalLayout_01"))
        self.GrupoC1label01_Caudal = QtGui.QLabel(Dialog)
        self.GrupoC1label01_Caudal.setObjectName(_fromUtf8("GrupoC1label01_Caudal"))
        self.GrupoC1verticalLayout_01.addWidget(self.GrupoC1label01_Caudal)
        self.GrupoC1label02_Velocidad = QtGui.QLabel(Dialog)
        self.GrupoC1label02_Velocidad.setObjectName(_fromUtf8("GrupoC1label02_Velocidad"))
        self.GrupoC1verticalLayout_01.addWidget(self.GrupoC1label02_Velocidad)
        self.horizontalLayoutC_Nivel04.addLayout(self.GrupoC1verticalLayout_01)
        self.GrupoC2verticalLayout_02 = QtGui.QVBoxLayout()
        self.GrupoC2verticalLayout_02.setObjectName(_fromUtf8("GrupoC2verticalLayout_02"))
        self.GrupoC2line01_Caudal = QtGui.QLineEdit(Dialog)
        self.GrupoC2line01_Caudal.setObjectName(_fromUtf8("GrupoC2line01_Caudal"))
        self.GrupoC2verticalLayout_02.addWidget(self.GrupoC2line01_Caudal)
        self.GrupoC2line02_Velocidad = QtGui.QLineEdit(Dialog)
        self.GrupoC2line02_Velocidad.setObjectName(_fromUtf8("GrupoC2line02_Velocidad"))
        self.GrupoC2verticalLayout_02.addWidget(self.GrupoC2line02_Velocidad)
        self.horizontalLayoutC_Nivel04.addLayout(self.GrupoC2verticalLayout_02)
        self.GrupoC3verticalLayout_03 = QtGui.QVBoxLayout()
        self.GrupoC3verticalLayout_03.setObjectName(_fromUtf8("GrupoC3verticalLayout_03"))
        self.GrupoC3labelUnits01 = QtGui.QLabel(Dialog)
        self.GrupoC3labelUnits01.setObjectName(_fromUtf8("GrupoC3labelUnits01"))
        self.GrupoC3verticalLayout_03.addWidget(self.GrupoC3labelUnits01)
        self.GrupoC3labelUnits02 = QtGui.QLabel(Dialog)
        self.GrupoC3labelUnits02.setObjectName(_fromUtf8("GrupoC3labelUnits02"))
        self.GrupoC3verticalLayout_03.addWidget(self.GrupoC3labelUnits02)
        self.horizontalLayoutC_Nivel04.addLayout(self.GrupoC3verticalLayout_03)
        self.verticalLayoutC_Nivel03.addLayout(self.horizontalLayoutC_Nivel04)
        self.ButtonCalcularC = QtGui.QPushButton(Dialog)
        self.ButtonCalcularC.setObjectName(_fromUtf8("ButtonCalcularC"))
        self.verticalLayoutC_Nivel03.addWidget(self.ButtonCalcularC)
        self.labelFormulaC = QtGui.QLabel(Dialog)
        self.labelFormulaC.setObjectName(_fromUtf8("labelFormulaC"))
        self.verticalLayoutC_Nivel03.addWidget(self.labelFormulaC)
        self.labelResultadoArea = QtGui.QLabel(Dialog)
        self.labelResultadoArea.setText(_fromUtf8(""))
        self.labelResultadoArea.setObjectName(_fromUtf8("labelResultadoArea"))
        self.verticalLayoutC_Nivel03.addWidget(self.labelResultadoArea)
        self.horizontalLayoutA_Nivel02.addLayout(self.verticalLayoutC_Nivel03)
        self.verticalLayoutA_Nivel01.addLayout(self.horizontalLayoutA_Nivel02)
        self.gridLayout.addLayout(self.verticalLayoutA_Nivel01, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Caudal", None))
        self.label_Titulo.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600; color:#3465a4;\">CALCULADORA DE CAUDAL TRES CASOS</span></p></body></html>", None))
        self.GrupoA1label01_Velocidad.setText(_translate("Dialog", "Velocidad", None))
        self.GrupoA1label02_Area.setText(_translate("Dialog", "Area", None))
        self.GrupoA3labelUnits01.setText(_translate("Dialog", "m/s", None))
        self.GrupoA3labelUnits02.setText(_translate("Dialog", "m**2", None))
        self.ButtonCalcularA.setText(_translate("Dialog", "Calcular Caudal", None))
        self.labelFormulaA.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Q=V*A</p></body></html>", None))
        self.GrupoB1label01_Caudal.setText(_translate("Dialog", "Caudal", None))
        self.GrupoB1label02_Area.setText(_translate("Dialog", "Area", None))
        self.GrupoB3labelUnits01.setText(_translate("Dialog", "m**3/s", None))
        self.GrupoB3labelUnits02.setText(_translate("Dialog", "m**2", None))
        self.ButtonCalcularB.setText(_translate("Dialog", "Calcular Velocidad", None))
        self.labelFormulaB.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">V=Q/A</p></body></html>", None))
        self.GrupoC1label01_Caudal.setText(_translate("Dialog", "Caudal", None))
        self.GrupoC1label02_Velocidad.setText(_translate("Dialog", "Velocidad", None))
        self.GrupoC3labelUnits01.setText(_translate("Dialog", "m**3/s", None))
        self.GrupoC3labelUnits02.setText(_translate("Dialog", "m/s", None))
        self.ButtonCalcularC.setText(_translate("Dialog", "Calcular Area", None))
        self.labelFormulaC.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">A=Q/V</p></body></html>", None))

